[server]
headless = true
runOnSave = false
fileWatcherType = "none"

[theme]
base = "dark"
primaryColor = "#3b82f6"
backgroundColor = "#0e1117"
secondaryBackgroundColor = "#262730"
textColor = "#fafafa"
font = "sans serif"

